Added cr7ia support
ros-industrial/fanuc_experimental pull request #35
Opened 2017-07-29 02:46 UTC by dniewinski

Added cr7ia support and a moveit config since I was working in this realm anyway

2017-07-29 03:06 UTC, dniewinski commented
Tests passed on my machine. I'll look on monday

2017-07-29 06:46 UTC, gavanderhoorn commented
Thanks for the PR again.

It's not the `roslaunch_test` that is failing, but the install phase:

```
Errors     << fanuc_cr7ia_moveit_config:install /root/catkin_ws/logs/fanuc_cr7ia_moveit_config/build.install.000.log

CMake Error at cmake_install.cmake:141 (FILE):

  file INSTALL cannot find

  "/root/catkin_ws/src/fanuc_experimental/fanuc_cr7ia_moveit_config/readme.md".
```

you probably copied the `CMakeLists.txt` from the `/L` MoveIt Config, but forgot to add `readme.md`.

2017-07-29 07:07 UTC, gavanderhoorn requested changes
Nice PR, thanks for this.

In addition to the small in-line comments, two things:

 1. could you please copy the `moveit.rviz` file from the `/L` moveit cfg to this one?
 1. we try to share meshes between robot variants as much as possible, and in this case I think only `link_2` and `link_4` are different. We try to exploit this by moving all shared meshes to a directory for the 'base model' (ie: `meshes/cr7ia`), and then create a variant specific subdir (`meshes/cr7ial`) that contains just the `visual` and `collision` meshes for the links that are different. So in this case `link_2.stl` and `link_4.stl`. See the [fanuc_lrmate200ic_support](https://github.com/ros-industrial/fanuc/tree/ef411f5e7703ae7dab6ccfacd17070cb5b2c31da/fanuc_lrmate200ic_support/meshes) pkg for an example.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_moveit_config/.setup_assistant
> +    relative_path: urdf/cr7ia.xacro
This will require enabling Jade+ xacro on Indigo again. See the `/L` moveit cfg.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_moveit_config/CMakeLists.txt
> +install(FILES readme.md DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
This is where <del>the test</del> Travis failed.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_moveit_config/config/ompl_planning.yaml
> +manipulator:
Please add the default planner entry here again.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_moveit_config/launch/planning_context.launch
> +  <param if="$(arg load_robot_description)" name="$(arg robot_description)" command="$(find xacro)/xacro.py '$(find fanuc_cr7ia_support)/urdf/cr7ia.xacro'"/>
I think this will need `--inorder`, like the `/L` launch file.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_moveit_config/launch/planning_context.launch
> +  <param if="$(arg load_robot_description)" name="$(arg robot_description)" command="$(find xacro)/xacro.py '$(find fanuc_cr7ia_support)/urdf/cr7ia.xacro'"/>
And remove the `.py` - it's deprecated.

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_support/package.xml
> +      /L model
standard -> base

2017-07-29 07:07 UTC, gavanderhoorn commented on fanuc_cr7ia_support/package.xml
> +      /L model
And the full stop seems to have gone missing ;)

2017-07-31 16:02 UTC, dniewinski commented on fanuc_cr7ia_moveit_config/config/ompl_planning.yaml
> +manipulator:
Done

2017-07-31 16:02 UTC, dniewinski commented
Meshes simplified to extend cr7ia

2017-08-10 12:28 UTC, dniewinski commented
Just a quick check-in on this PR.  Are you waiting on anything from me?

2017-08-10 12:41 UTC, gavanderhoorn commented
No, I'm just really busy. I'll take a look probably tomorrow.

Thanks already so far 👍.

2017-10-06 13:33 UTC, gavanderhoorn commented
Just waiting for Travis to finish.

2017-10-06 14:34 UTC, gavanderhoorn reviewed
I think this is OK now.

2017-10-06 14:35 UTC, gavanderhoorn commented
Thanks again for the PR, and my apologies for only getting back to it again after some time.

2017-10-06 14:35 UTC, merged