Adding support for crx10ial
ros-industrial/fanuc_experimental pull request #67
Opened 2022-02-14 18:24 UTC by demorise

![crx10_collision_model](https://user-images.githubusercontent.com/22728175/153923606-5a9cfede-3fb6-4612-91b2-4fc2e9e32c35.png)

2022-02-23 16:28 UTC, gavanderhoorn commented
Thanks for the PR. It's certainly appreciated.

I've been rather busy with other things. I'll take a look at a later time.

2022-03-30 10:25 UTC, gavanderhoorn commented
I've pushed a few fixup commits and submitted a PR @demorise.

See https://github.com/WILDER-SYSTEMS-LLC/fanuc_experimental/pull/1.

2022-03-30 13:44 UTC, demorise commented
> I've pushed a few fixup commits and submitted a PR @demorise.
> 
> See [WILDER-SYSTEMS-LLC#1](https://github.com/WILDER-SYSTEMS-LLC/fanuc_experimental/pull/1).

Thanks @gavanderhoorn . Is there any action I need to take from my end?

2022-03-30 13:50 UTC, gavanderhoorn commented
If you agree with my proposed changes, you could merge the PR.

2022-03-30 15:12 UTC, gavanderhoorn requested changes
Some additional comments.

2022-03-30 15:12 UTC, gavanderhoorn commented on fanuc_experimental/package.xml
> +  <exec_depend>fanuc_crx10ia_support</exec_depend>
Missed this one: could you please keep the list alphabetically sorted?

2022-03-30 15:12 UTC, gavanderhoorn commented on fanuc_crx10ia_support/package.xml
> +      <li>CRX-10iA/L - 1418mm reach</li>
Normally we list whether the model was created based on the regular joint limits (for J1 fi) or the extended ones, or whether a hollow-wrist config was used or not.

I don't believe the CRX-10iA/L has those kind of configuration options, so this is OK for now.

2022-03-30 15:12 UTC, gavanderhoorn commented on fanuc_crx10ia_support/readme.md
> +[fanuc][] page on the ROS wiki for more information on usage.
```suggestion
[fanuc_experimental][] page on the ROS wiki for more information on usage.
```

2022-03-30 15:12 UTC, gavanderhoorn commented on fanuc_crx10ia_support/readme.md
> +[fanuc]: http://wiki.ros.org/fanuc
```suggestion
[fanuc_experimental]: http://wiki.ros.org/fanuc_experimental
```

2022-03-30 15:13 UTC, gavanderhoorn commented on fanuc_crx10ia_support/package.xml
> +      <li>CRX-10iA/L - 1418mm reach</li>
This is not an action for you. Just wanted to add a note here.

2022-03-30 15:31 UTC, demorise commented
I have made the changes and pushed a new commit.

2022-03-30 16:32 UTC, gavanderhoorn commented
For your next PR: Github makes accepting suggestions really easy. Just click the button(s) in the comments in the web ui.

2022-03-30 16:33 UTC, gavanderhoorn commented
Apparently Actions needed a nudge.

2022-03-30 18:03 UTC, demorise commented
> For your next PR: Github makes accepting suggestions really easy. Just click the button(s) in the comments in the web ui.

Thanks!

2022-03-30 18:51 UTC, gavanderhoorn approved these changes
Alright, this looks OK now.

Thanks again for the PR @demorise, and thanks for iterating on it with me.

:+1:

2022-03-30 18:52 UTC, gavanderhoorn commented
I'll use a squash-merge, as we don't need all the fixups to end up in the repository's commit history.

2022-03-30 18:52 UTC, merged

2022-03-30 18:53 UTC, gavanderhoorn commented
Thanks again @demorise.

Note that because I used a squash-merge, Github may not let you know you can delete the branch.

2022-03-30 19:05 UTC, demorise commented
> Thanks again @demorise.
> 
> Note that because I used a squash-merge, Github may not let you know you can delete the branch.

No worries!